version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./scores:/app/scores  # Map local 'scores' directory to container's '/app/scores'
    environment:
      - FLASK_ENV=development
