version: '3.8'

services:
  web:
    build: .
    ports:
      - "8777:8777"
    environment:
      - USERNAME=<votre_nom_utilisateur>
    command: python main_scores.py
    volumes:
      - ./scores:/app/scores
